log_level: INFO

engines:
  pmd:
    rulesets:
      - "./custom-rules/pmd/custom-pmd-ruleset.xml"
    file_extensions:
      - .cls
      - .trigger

  eslint:
    eslint_config_file: "./.eslintrc.json"
    file_extensions:
      - .js
