engines:
  eslint:
    enabled: true
    config: ./.eslintrc.json
    file_extensions:
      javascript: [".js", ".ts", ".js-meta.xml"]
    env:
      node: true
    options: "--resolve-plugins-relative-to ."
    exclude:
      - "**/node_modules/**"
      - "**/staticresources/**"
      - "**/__tests__/**"

  pmd:
    enabled: true
    rulesets: "./custom-rules/pmd/custom-pmd-ruleset.xml"
    file_extensions:
      apex: [".cls", ".trigger"]
    exclude:
      - "**/Test.cls"
      - "**/*Test.cls"
    version: "6.55.0"

project:
  sourcePaths:
    - "force-app/main/default"
  apiVersion: "58.0"

general:
  workingDirectory: .
  failOnError: false
  output:
    format: "json"
    path: "debug/"
