engines:
  pmd:
    custom_rulesets:
      - "./custom-rules/pmd/custom-pmd-ruleset.xml"

  eslint:
    eslint_config_file: "./.eslintrc.json"
    disable_javascript_base_config: true
    disable_lwc_base_config: true
    disable_typescript_base_config: true
