engines:
  pmd:
    custom_rulesets:
      - "./custom-rules/pmd/custom-pmd-ruleset.xml"
    file_extensions:
      cls: true
      trigger: true

  eslint:
    eslint_config_file: "./.eslintrc.json"
    disable_javascript_base_config: true
    disable_lwc_base_config: true
    disable_typescript_base_config: true
    file_extensions:
      js: true
