engines:
  pmd:
    enabled: true
    targetPatterns:
      - "force-app/**/*.cls"
      - "force-app/**/*.trigger"
    rulesets:
      - "./custom-rules/pmd/custom-pmd-ruleset.xml"

  eslint:
    enabled: true
    targetPatterns:
      - "force-app/**/*.js"
    config: "./.eslintrc.json"

log_level: INFO
