//chat constant
export const CHAT_STATUS = {
    COMPLETE: 'CHAT_STATUS_COMPLETE',
    INPROGRESS: 'CHAT_STATUS_INPROGRESS'
}


//consult constant
export const DISABLE_COACHING_REQUEST= "DISABLE_COACHING_REQUEST";
export const ENABLE_COACHING_REQUEST = "ENABLE_COACHING_REQUEST";
export const DISABLE_ONGOING_CONSULT_REQUEST = "DISABLE_ONGOING_CONSULT_REQUEST"
export const ENABLE_ONGOING_CONSULT_REQUEST = "ENABLE_ONGOING_CONSULT_REQUEST"