name: Salesforce Dependency Analyzer
on:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Comma-separated list of branches to analyze'
        required: true
      base_ref:
        description: 'Base branch/reference'
        required: true
        default: 'main'
      sfdx_project_path:
        description: 'Path to sfdx-project.json'
        required: false
        default: './'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify scripts directory exists
      run: |
        echo "Current directory structure:"
        ls -la
        echo "Checking scripts directory..."
        if [ ! -d "scripts" ]; then
          echo "Error: scripts directory not found"
          ls -la
          exit 1
        fi
        echo "Contents of scripts directory:"
        ls -la scripts/

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx gitpython python-dotenv pyyaml

    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sfdx --version

    - name: Install Node.js dependencies
      run: |
        npm install -g @salesforce/source-deploy-retrieve ts-node
        npm install fast-xml-parser glob@9 lodash @salesforce/core @salesforce/source-deploy-retrieve --legacy-peer-deps

    - name: Run full analysis
      id: analysis
      run: |
        echo "Current working directory: $PWD"
        echo "Running analysis from repository root..."
        cd scripts
        echo "Now in: $PWD"
        ls -la
        git fetch --all
        npx ts-node analyze.ts "${{ inputs.branches }}" "${{ inputs.base_ref }}" "${{ inputs.sfdx_project_path }}"
        python generate_plan.py
        cd ..

    - name: Verify output files
      run: |
        echo "Checking for output files in scripts directory:"
        ls -la scripts/*.json scripts/*.html || echo "No output files found"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-analysis
        path: |
          scripts/change_sets.json
          scripts/deployment_plan.json
          scripts/dependency_graph.json
          scripts/dependency_report.html
