name: Salesforce Dependency Analyzer
on:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Comma-separated list of branches to analyze'
        required: true
      base_ref:
        description: 'Base branch/reference'
        required: true
        default: 'main'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx gitpython python-dotenv pyyaml
        npm install -g @salesforce/cli ts-node
        npm install fast-xml-parser glob lodash @salesforce/source-deploy-retrieve

    - name: Run analysis
      working-directory: ./scripts
      run: |
        git fetch --all
        npx ts-node analyze.ts "${{ inputs.branches }}" "${{ inputs.base_ref }}"
        python generate_plan.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-analysis
        path: |
          scripts/change_sets.json
          scripts/deployment_plan.json
          scripts/dependency_graph.json
          scripts/dependency_report.html
