name: Salesforce Dependency Analyzer
on:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Comma-separated list of branches to analyze'
        required: true
      base_ref:
        description: 'Base branch/reference'
        required: true
        default: 'main'
      sfdx_project_path:
        description: 'Path to sfdx-project.json'
        required: false
        default: './'

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx gitpython python-dotenv pyyaml

    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sfdx --version

    - name: Install Node.js dependencies
      run: |
        npm install -g @salesforce/source-deploy-retrieve ts-node
        npm install fast-xml-parser glob@9 lodash @salesforce/core @salesforce/source-deploy-retrieve --legacy-peer-deps

    - name: Verify files exist
      run: |
        ls -la
        echo "Checking for analysis files..."
        [ -f analyze.ts ] || exit 1
        [ -f generate_plan.py ] || exit 1
        echo "All required files present"

    - name: Run full analysis
      id: analysis
      run: |
        git fetch --all
        npx ts-node ./analyze.ts "${{ inputs.branches }}" "${{ inputs.base_ref }}" "${{ inputs.sfdx_project_path }}"
        python ./generate_plan.py

    - name: Verify output files
      run: |
        [ -f change_sets.json ] || echo "change_sets.json not found"
        [ -f deployment_plan.json ] || echo "deployment_plan.json not found"
        [ -f dependency_graph.json ] || echo "dependency_graph.json not found"
        [ -f dependency_report.html ] || echo "dependency_report.html not found"
        ls -la *.json *.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-analysis
        path: |
          change_sets.json
          deployment_plan.json
          dependency_graph.json
          dependency_report.html
