name: Advanced Salesforce Rollback

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release branch name (e.g., R1)'
        required: true
      features_to_rollback:
        description: 'Comma-separated list of feature branches to rollback (e.g., F1,F2)'
        required: true
      dry_run:
        description: 'Run in dry-run mode (no actual changes)'
        required: false
        default: 'false'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get full history immediately
        ref: ${{ github.ref }}  # Explicitly checkout the correct ref

    - name: Setup Git environment
      run: |
        # Safe directory for GitHub Actions
        git config --global --add safe.directory /github/workspace
        
        # Fetch all branches and tags (no --unshallow needed)
        git fetch --all --tags
        
        # Debug: Show branch information
        echo "--- Git Branch Info ---"
        git branch -a
        git show-ref --heads
        echo "-----------------------"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Debug branch info
      run: |
        git branch -a
        git show-ref
        git remote -v

    - name: Execute rollback
      run: |
        
        python -m rollback_system.main \
          --release-branch "${{ inputs.release_branch }}" \
          --features "${{ inputs.features_to_rollback }}" \
          --dry-run
          
    - name: Upload rollback report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rollback-report
        path: rollback_report.json
