name: Targeted SFDX Scanner Scan (Commit Based)

on:
  workflow_dispatch:
    inputs:
      userStoryId:
        required: false
      userStoryCommitId:
        required: false
      commitId:
        required: true

jobs:
  sfdx-scanner-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.commitId }}

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
    
      - name: Install Salesforce CLI and Scanner Plugin
        run: |
          npm install --global @salesforce/cli@latest
          sf plugins install @salesforce/sfdx-scanner
          sudo apt-get update && sudo apt-get install -y jq
          sf --version
          sf plugins --core
  
      - name: Extract Changed Lines
        run: |
          mkdir -p results
          echo "Extracting changed lines for commit: ${{ github.event.inputs.commitId }}"
          git show --unified=0 -w ${{ github.event.inputs.commitId }} | awk '
            /^diff --git/ {
              if (filename) print "";
              filename = $3;
              sub("a/", "", filename);
              if (filename ~ /\.(cls|trigger|js|html|css|xml)$/) {
                print "FILE:" filename
              } else {
                filename = ""
              }
            }
            /^@@/ {
              if (filename == "") next;
              match($0, /\+([0-9]+)(,([0-9]+))?/, m);
              start = m[1];
              count = m[3] ? m[3] : 1;
              for (i = 0; i < count; i++) print "LINE:" start + i
            }
          ' > results/changed_lines.txt

      - name: Run SFDX Scanner for Apex and LWC (Committed Files Only)
        run: |
          mkdir -p debug
          apex_files=()
          lwc_files=()

          # Read changed file paths
          while read -r line; do
            if [[ "$line" == FILE:* ]]; then
              file="${line#FILE:}"
              if [[ "$file" == *.cls || "$file" == *.trigger ]]; then
                apex_files+=("$file")
              elif [[ "$file" == *.js || "$file" == *.html || "$file" == *.css ]]; then
                lwc_files+=("$file")
              fi
            fi
          done < results/changed_lines.txt

          # Run Apex scan if files exist
          if [ ${#apex_files[@]} -gt 0 ]; then
            echo "Running Apex scan on committed files only"
            sf scanner run --format json --engine pmd --target "${apex_files[@]}" --outfile debug/apex_scan.json || echo "Apex scan complete"
          else
            echo "No Apex files changed in this commit"
            echo "[]" > debug/apex_scan.json
          fi

          # Run LWC scan using sfdx scanner (ESLint engine)
          if [ ${#lwc_files[@]} -gt 0 ]; then
            echo "Running LWC scan on committed JS files only"
            
            echo "Files being scanned:"
            printf '%s\n' "${lwc_files[@]}"
          
            # Run the scanner only on committed .js files
            sf scanner run --engine eslint --format json --target "${lwc_files[@]}" --outfile debug/lwc_scan.json || echo "LWC scan completed with violations"
          else
            echo "No LWC JS files changed in this commit"
            echo "[]" > debug/lwc_scan.json
          fi



      - name: Filter Violations by Changed Lines
        run: |
          echo "[]" > debug/filtered.json
          current_file=""
          changed_lines=()

          while read -r line; do
            if [[ "$line" == FILE:* ]]; then
              if [[ -n "$current_file" && ${#changed_lines[@]} -gt 0 ]]; then
                changed_json=$(printf '%d\n' "${changed_lines[@]}" | jq -s '.')
                for scan_file in debug/apex_scan.json debug/lwc_scan.json; do
                  jq --arg path "$current_file" --argjson changed "$changed_json" '
                    .[] | select(.filePath == $path) | {
                      filePath: $path,
                      violations: [
                        .violations[] | select((.line | tonumber) as $line | $changed | index($line) != null)
                      ]
                    } | select(.violations | length > 0)
                  ' "$scan_file" >> debug/filtered.json || true
                done
              fi
              current_file="${line#FILE:}"
              changed_lines=()
            elif [[ "$line" == LINE:* ]]; then
              changed_lines+=("${line#LINE:}")
            fi
          done < results/changed_lines.txt

          # Process last file
          if [[ -n "$current_file" && ${#changed_lines[@]} -gt 0 ]]; then
            changed_json=$(printf '%d\n' "${changed_lines[@]}" | jq -s '.')
            for scan_file in debug/apex_scan.json debug/lwc_scan.json; do
              jq --arg path "$current_file" --argjson changed "$changed_json" '
                .[] | select(.filePath == $path) | {
                  filePath: $path,
                  violations: [
                    .violations[] | select((.line | tonumber) as $line | $changed | index($line) != null)
                  ]
                } | select(.violations | length > 0)
              ' "$scan_file" >> debug/filtered.json || true
            done
          fi

          jq -s '.' debug/filtered.json > results/output.json

      # - name: Verify Config File Exists
      #   run: |
      #     echo "Listing contents of root directory:"
      #     ls -la
      #     echo "Content of scanner-config.json (if exists):"
      #     cat scanner-config.json || echo "scanner-config.json not found"

        


      - name: Debug Output Files
        run: |
          echo "=== Changed Lines ==="
          cat results/changed_lines.txt
          echo "=== Output JSON ==="
          cat results/output.json || echo "No output.json found"
          echo "=== Payload JSON ==="
          cat payload.json || echo "No payload.json found"

      - name: Prepare Payload
        run: |
          jq -n \
            --arg userStoryId "${{ github.event.inputs.userStoryId }}" \
            --arg userStoryCommitId "${{ github.event.inputs.userStoryCommitId }}" \
            --arg commitId "${{ github.event.inputs.commitId }}" \
            --arg run_id "${{ github.run_id }}" \
            --slurpfile violations results/output.json \
            '{
              userStoryId: $userStoryId,
              userStoryCommitId: $userStoryCommitId,
              commitId: $commitId,
              run_id: $run_id,
              violations: $violations[0]
            }' > payload.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sfdx-scanner-violations
          path: payload.json
