name: Targeted SFDX Scanner Scan (Commit Based)

on:
  workflow_dispatch:
    inputs:
      userStoryId:
        required: false
      userStoryCommitId:
        required: false
      commitId:
        required: true

jobs:
  sfdx-scanner-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.commitId }}

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI and Scanner
        run: |
          npm install --global @salesforce/cli@latest
          sf plugins install @salesforce/plugin-code-analyzer@latest
          sudo apt-get update && sudo apt-get install -y jq
          sf --version
          sf plugins --core

      - name: Create .eslintrc.json
        run: |
          cat <<EOF > .eslintrc.json
          {
            "extends": ["@salesforce/eslint-config-lwc/recommended"],
            "plugins": ["@lwc/lwc"],
            "env": {
              "browser": true,
              "es2021": true,
              "node": true
            }
          }
          EOF

      - name: Extract Changed Lines
        run: |
          mkdir -p results
          git show --unified=0 -w ${{ github.event.inputs.commitId }} | awk '
            /^diff --git/ {
              if (filename) print "";
              filename = $3;
              sub("a/", "", filename);
              if (filename ~ /\.(cls|trigger|js)$/) {
                print "FILE:" filename
              } else {
                filename = ""
              }
            }
            /^@@/ {
              if (filename == "") next;
              match($0, /\+([0-9]+)(,([0-9]+))?/, m);
              start = m[1];
              count = m[3] ? m[3] : 1;
              for (i = 0; i < count; i++) print "LINE:" start + i
            }
          ' > results/changed_lines.txt

      - name: Run Scans on Changed Files
        run: |
          mkdir -p debug results
          echo "[]" > results/output.json
          echo "" > debug/filtered.json

          current_file=""
          while read -r line; do
            if [[ "$line" == FILE:* ]]; then
              if [[ -n "$current_file" && -f "$current_file" ]]; then
                ext="${current_file##*.}"
                changed_json=$(printf '%d\n' "${changed_lines[@]}" | jq -s '.')

                if [[ "$ext" == "cls" || "$ext" == "trigger" ]]; then
                  sf scanner run --target "$current_file" --engine pmd --format json --outfile "debug/raw_${current_file//\//_}.json"
                elif [[ "$ext" == "js" ]]; then
                  npx eslint "$current_file" -f json -c .eslintrc.json > "debug/raw_${current_file//\//_}.json"
                fi

                if jq -e '.[0].messages? or .violations? or .results[0].violations?' "debug/raw_${current_file//\//_}.json" >/dev/null; then
                  jq --arg original_path "$current_file" --argjson changed "$changed_json" '
                    .[0].messages? // .violations? // .results[0].violations // [] |
                    map(select((.line | tonumber) as $line | $changed | index($line) != null)) |
                    select(length > 0) |
                    {filePath: $original_path, violations: .}
                  ' "debug/raw_${current_file//\//_}.json" >> debug/filtered.json
                fi
              fi
              current_file="${line#FILE:}"
              changed_lines=()
            elif [[ "$line" == LINE:* ]]; then
              changed_lines+=("${line#LINE:}")
            fi
          done < results/changed_lines.txt

          if [[ -n "$current_file" && -f "$current_file" && ${#changed_lines[@]} -gt 0 ]]; then
            ext="${current_file##*.}"
            changed_json=$(printf '%d\n' "${changed_lines[@]}" | jq -s '.')
            if [[ "$ext" == "cls" || "$ext" == "trigger" ]]; then
              sf scanner run --target "$current_file" --engine pmd --format json --outfile "debug/raw_${current_file//\//_}.json"
            elif [[ "$ext" == "js" ]]; then
              npx eslint "$current_file" -f json -c .eslintrc.json > "debug/raw_${current_file//\//_}.json"
            fi
            if jq -e '.[0].messages? or .violations? or .results[0].violations?' "debug/raw_${current_file//\//_}.json" >/dev/null; then
              jq --arg original_path "$current_file" --argjson changed "$changed_json" '
                .[0].messages? // .violations? // .results[0].violations // [] |
                map(select((.line | tonumber) as $line | $changed | index($line) != null)) |
                select(length > 0) |
                {filePath: $original_path, violations: .}
              ' "debug/raw_${current_file//\//_}.json" >> debug/filtered.json
            fi
          fi

          if [[ -s debug/filtered.json ]]; then
            jq -c '.' debug/filtered.json > debug/filtered_line.json
            jq -s '.' debug/filtered_line.json > results/output.json
          else
            echo "[]" > results/output.json
          fi

      - name: Prepare Payload
        run: |
          jq -n \
            --arg userStoryId "${{ github.event.inputs.userStoryId }}" \
            --arg userStoryCommitId "${{ github.event.inputs.userStoryCommitId }}" \
            --arg commitId "${{ github.event.inputs.commitId }}" \
            --arg run_id "${{ github.run_id }}" \
            --slurpfile violations results/output.json \
            '{
              userStoryId: $userStoryId,
              userStoryCommitId: $userStoryCommitId,
              commitId: $commitId,
              run_id: $run_id,
              violations: $violations[0]
            }' > payload.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sfdx-scanner-violations
          path: payload.json
